"""erp.views — page-level view modules for IRONLINE ACCESS ERP."""

__all__ = [
    "admin",
    "asset",
    "closeworkorder",
    "customers",
    "dashboard",
    "deployment",
    "currentdeployment",
    "customerreport",
    "fleetstatus",
    "workorderreport",
    "fleetutil",
    "login",
    "machinehistory",
    "wlreports",
    "machine",
    "operator",
    "site",
    "worklog",
    "worklogreport",
    "workorder",
    "invoice",
]
