"""erp.views — page-level view modules for IRONLINE ACCESS ERP."""

__all__ = [
    "admin",
    "advance_management",
    "asset",
    "closeworkorder",
    "conveyance_rules",
    "customers",
    "customerreport",
    "dashboard",
    "deployment",
    "currentdeployment",
    "fleetstatus",
    "fleetutil",
    "invoice",
    "invoicereport",
    "login",
    "machinecompliance",
    "machinehistory",
    "machinemovement",
    "machinesale",
    "machine",
    "operatorreport",
    "operator",
    "payroll_inputs",
    "pf_payments",
    "site",
    "wldetailreport",
    "wlreports",
    "worklog",
    "worklogreport",
    "workorder",
    "workorderreport",
]
